apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tmaestro
  name: tmaestro
spec:
  selector:
    matchLabels:
      app: tmaestro
  replicas: 1
  template:
    metadata:
      labels:
        app: tmaestro
    spec:
      containers:
        - image: REPLACE_WITH_TMAESTRO_IMAGE
          imagePullPolicy: Never
          name: tmaestro-server
          ports:
            - containerPort: 9001
            - containerPort: 9000
          env:
            - name: TMAESTRO_SERVER_IP
              value: "localhost"
            - name: TMAESTRO_SERVER_DOMAIN
              value: "tmaestro:9001"
            - name: TMAESTRO_WEB_HOME
              value: "localhost:30083"
            ## <GRPC config>  ##
            - name: GRPC_SERVER_IP
              value: "tmaestro"
            - name: GRPC_SERVER_PORT
              value: "9000"
            ## <ALGO config>  ##
            - name: ALGO_PARAM_TUNING_URL
              value: "http://localhost:30084"
          volumeMounts:
            - name: tmaestro
              mountPath: "/opt/app/storage"
              readOnly: true
      volumes:
        - name: tmaestro
          configMap:
            name: tmaestro-kube-config
---
apiVersion: v1
kind: Service
metadata:
  name: tmaestro
spec:
  ports:
    - port: 9001
      name: http
      targetPort: 9001
      nodePort: 30081
      protocol: TCP
    - port: 9000
      name: grpc
      protocol: TCP
      targetPort: 9000
      nodePort: 30082
    - port: 8080
      name: front-http
      targetPort: 80
      nodePort: 30083
      protocol: TCP
    - port: 5000
      name: alog-tune-domain-url
      targetPort: 5000
      nodePort: 30084
    - port: 9091
      name: alog-intelligent-url
      targetPort: 9091
      nodePort: 30085
    - port: 9099       # Minio console port
      name: minioconsole
      targetPort: 9099
      nodePort: 30086
      protocol: TCP
    - port: 9098      # Minio server api port
      name: minioapi
      targetPort: 9098
      nodePort: 30087
      protocol: TCP
  type: NodePort
  selector:
    app: tmaestro