#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Feature Request
labels: ["enhancement"]
description: Suggest an idea to container-auto-tune
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill this!
  - type: textarea
    id: feat-description
    attributes:
      label: Describe This Feature
      description: A clear and concise description of what the Feature is. 
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: assign
    attributes:
      label: Assgin People
      description: If possible, please assign the people to fix this issue.
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Maybe you have considered some ideas or solutions about this feature.
    validations:
      required: true
  - type: textarea
    id: ac
    attributes:
      label: Acceptance criteria (AC)
      description: If possible, please give the ac for feature when it was finished.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.
