/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * This file is generated by jOOQ.
 */
package com.alipay.autotuneservice.dao.jooq.tables;


import com.alipay.autotuneservice.dao.jooq.Keys;
import com.alipay.autotuneservice.dao.jooq.TmaestroLite;
import com.alipay.autotuneservice.dao.jooq.tables.records.TuningParamTaskDataRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row21;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TuningParamTaskData extends TableImpl<TuningParamTaskDataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA</code>
     */
    public static final TuningParamTaskData TUNING_PARAM_TASK_DATA = new TuningParamTaskData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TuningParamTaskDataRecord> getRecordType() {
        return TuningParamTaskDataRecord.class;
    }

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.PIPELINE_ID</code>.
     */
    public final TableField<TuningParamTaskDataRecord, Integer> PIPELINE_ID = createField(DSL.name("PIPELINE_ID"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.APP_ID</code>.
     */
    public final TableField<TuningParamTaskDataRecord, Integer> APP_ID = createField(DSL.name("APP_ID"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.APP_NAME</code>.
     */
    public final TableField<TuningParamTaskDataRecord, String> APP_NAME = createField(DSL.name("APP_NAME"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.PODS</code>.
     */
    public final TableField<TuningParamTaskDataRecord, String> PODS = createField(DSL.name("PODS"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.OPTIMIZATION_TYPE</code>.
     */
    public final TableField<TuningParamTaskDataRecord, String> OPTIMIZATION_TYPE = createField(DSL.name("OPTIMIZATION_TYPE"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.PROBLEM_DESCRIBE</code>.
     */
    public final TableField<TuningParamTaskDataRecord, String> PROBLEM_DESCRIBE = createField(DSL.name("PROBLEM_DESCRIBE"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.PROBLEM_TYPE</code>.
     */
    public final TableField<TuningParamTaskDataRecord, String> PROBLEM_TYPE = createField(DSL.name("PROBLEM_TYPE"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.DIRECTION</code>.
     */
    public final TableField<TuningParamTaskDataRecord, String> DIRECTION = createField(DSL.name("DIRECTION"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.TRIAL_NUMS</code>.
     */
    public final TableField<TuningParamTaskDataRecord, Integer> TRIAL_NUMS = createField(DSL.name("TRIAL_NUMS"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.TRIAL_PARAMS</code>.
     */
    public final TableField<TuningParamTaskDataRecord, String> TRIAL_PARAMS = createField(DSL.name("TRIAL_PARAMS"), SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.MAX_ITER</code>.
     */
    public final TableField<TuningParamTaskDataRecord, Integer> MAX_ITER = createField(DSL.name("MAX_ITER"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.TRIAL_TIME_MIN</code>.
     */
    public final TableField<TuningParamTaskDataRecord, Integer> TRIAL_TIME_MIN = createField(DSL.name("TRIAL_TIME_MIN"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.TRIAL_TIME_MAX</code>.
     */
    public final TableField<TuningParamTaskDataRecord, Integer> TRIAL_TIME_MAX = createField(DSL.name("TRIAL_TIME_MAX"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.TRIAL_START_TIME</code>.
     */
    public final TableField<TuningParamTaskDataRecord, LocalDateTime> TRIAL_START_TIME = createField(DSL.name("TRIAL_START_TIME"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.TRIAL_STOP_TIME</code>.
     */
    public final TableField<TuningParamTaskDataRecord, LocalDateTime> TRIAL_STOP_TIME = createField(DSL.name("TRIAL_STOP_TIME"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.START_TIME</code>.
     */
    public final TableField<TuningParamTaskDataRecord, LocalDateTime> START_TIME = createField(DSL.name("START_TIME"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.END_TIME</code>.
     */
    public final TableField<TuningParamTaskDataRecord, LocalDateTime> END_TIME = createField(DSL.name("END_TIME"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.TASK_STATUS</code>.
     */
    public final TableField<TuningParamTaskDataRecord, String> TASK_STATUS = createField(DSL.name("TASK_STATUS"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.BEFORE_PARAMS</code>.
     */
    public final TableField<TuningParamTaskDataRecord, String> BEFORE_PARAMS = createField(DSL.name("BEFORE_PARAMS"), SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.MODIFY_TIME</code>.
     */
    public final TableField<TuningParamTaskDataRecord, LocalDateTime> MODIFY_TIME = createField(DSL.name("MODIFY_TIME"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA.COMPARE_PODS</code>.
     */
    public final TableField<TuningParamTaskDataRecord, String> COMPARE_PODS = createField(DSL.name("COMPARE_PODS"), SQLDataType.VARCHAR(1000), this, "");

    private TuningParamTaskData(Name alias, Table<TuningParamTaskDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private TuningParamTaskData(Name alias, Table<TuningParamTaskDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA</code> table reference
     */
    public TuningParamTaskData(String alias) {
        this(DSL.name(alias), TUNING_PARAM_TASK_DATA);
    }

    /**
     * Create an aliased <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA</code> table reference
     */
    public TuningParamTaskData(Name alias) {
        this(alias, TUNING_PARAM_TASK_DATA);
    }

    /**
     * Create a <code>TMAESTRO-LITE.TUNING_PARAM_TASK_DATA</code> table reference
     */
    public TuningParamTaskData() {
        this(DSL.name("TUNING_PARAM_TASK_DATA"), null);
    }

    public <O extends Record> TuningParamTaskData(Table<O> child, ForeignKey<O, TuningParamTaskDataRecord> key) {
        super(child, key, TUNING_PARAM_TASK_DATA);
    }

    @Override
    public Schema getSchema() {
        return TmaestroLite.TMAESTRO_LITE;
    }

    @Override
    public UniqueKey<TuningParamTaskDataRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_6E;
    }

    @Override
    public List<UniqueKey<TuningParamTaskDataRecord>> getKeys() {
        return Arrays.<UniqueKey<TuningParamTaskDataRecord>>asList(Keys.CONSTRAINT_6E);
    }

    @Override
    public TuningParamTaskData as(String alias) {
        return new TuningParamTaskData(DSL.name(alias), this);
    }

    @Override
    public TuningParamTaskData as(Name alias) {
        return new TuningParamTaskData(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TuningParamTaskData rename(String name) {
        return new TuningParamTaskData(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TuningParamTaskData rename(Name name) {
        return new TuningParamTaskData(name, null);
    }

    // -------------------------------------------------------------------------
    // Row21 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row21<Integer, Integer, String, String, String, String, String, String, Integer, String, Integer, Integer, Integer, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, String, String, LocalDateTime, String> fieldsRow() {
        return (Row21) super.fieldsRow();
    }
}
