/*
 * This file is generated by jOOQ.
 */
package com.alipay.autotuneservice.dao.jooq.tables;


import com.alipay.autotuneservice.dao.jooq.Keys;
import com.alipay.autotuneservice.dao.jooq.TmaestroLite;
import com.alipay.autotuneservice.dao.jooq.tables.records.TuningParamTaskInfoRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TuningParamTaskInfo extends TableImpl<TuningParamTaskInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>tmaestro-lite.tuning_param_task_info</code>
     */
    public static final TuningParamTaskInfo TUNING_PARAM_TASK_INFO = new TuningParamTaskInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TuningParamTaskInfoRecord> getRecordType() {
        return TuningParamTaskInfoRecord.class;
    }

    /**
     * The column <code>tmaestro-lite.tuning_param_task_info.info_id</code>.
     */
    public final TableField<TuningParamTaskInfoRecord, Long> INFO_ID = createField(DSL.name("info_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>tmaestro-lite.tuning_param_task_info.app_id</code>.
     */
    public final TableField<TuningParamTaskInfoRecord, Integer> APP_ID = createField(DSL.name("app_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>tmaestro-lite.tuning_param_task_info.app</code>.
     */
    public final TableField<TuningParamTaskInfoRecord, String> APP = createField(DSL.name("app"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>tmaestro-lite.tuning_param_task_info.optimization_type</code>.
     */
    public final TableField<TuningParamTaskInfoRecord, String> OPTIMIZATION_TYPE = createField(DSL.name("optimization_type"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>tmaestro-lite.tuning_param_task_info.problem_type</code>.
     */
    public final TableField<TuningParamTaskInfoRecord, String> PROBLEM_TYPE = createField(DSL.name("problem_type"), SQLDataType.VARCHAR(510), this, "");

    /**
     * The column <code>tmaestro-lite.tuning_param_task_info.param_distribution</code>.
     */
    public final TableField<TuningParamTaskInfoRecord, String> PARAM_DISTRIBUTION = createField(DSL.name("param_distribution"), SQLDataType.VARCHAR(2000), this, "");

    /**
     * The column <code>tmaestro-lite.tuning_param_task_info.problem_id</code>.
     */
    public final TableField<TuningParamTaskInfoRecord, String> PROBLEM_ID = createField(DSL.name("problem_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>tmaestro-lite.tuning_param_task_info.dt</code>.
     */
    public final TableField<TuningParamTaskInfoRecord, String> DT = createField(DSL.name("dt"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>tmaestro-lite.tuning_param_task_info.write_time</code>.
     */
    public final TableField<TuningParamTaskInfoRecord, LocalDateTime> WRITE_TIME = createField(DSL.name("write_time"), SQLDataType.LOCALDATETIME(0), this, "");

    private TuningParamTaskInfo(Name alias, Table<TuningParamTaskInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private TuningParamTaskInfo(Name alias, Table<TuningParamTaskInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>tmaestro-lite.tuning_param_task_info</code> table reference
     */
    public TuningParamTaskInfo(String alias) {
        this(DSL.name(alias), TUNING_PARAM_TASK_INFO);
    }

    /**
     * Create an aliased <code>tmaestro-lite.tuning_param_task_info</code> table reference
     */
    public TuningParamTaskInfo(Name alias) {
        this(alias, TUNING_PARAM_TASK_INFO);
    }

    /**
     * Create a <code>tmaestro-lite.tuning_param_task_info</code> table reference
     */
    public TuningParamTaskInfo() {
        this(DSL.name("tuning_param_task_info"), null);
    }

    public <O extends Record> TuningParamTaskInfo(Table<O> child, ForeignKey<O, TuningParamTaskInfoRecord> key) {
        super(child, key, TUNING_PARAM_TASK_INFO);
    }

    @Override
    public Schema getSchema() {
        return TmaestroLite.TMAESTRO_LITE;
    }

    @Override
    public Identity<TuningParamTaskInfoRecord, Long> getIdentity() {
        return (Identity<TuningParamTaskInfoRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TuningParamTaskInfoRecord> getPrimaryKey() {
        return Keys.KEY_TUNING_PARAM_TASK_INFO_PRIMARY;
    }

    @Override
    public List<UniqueKey<TuningParamTaskInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<TuningParamTaskInfoRecord>>asList(Keys.KEY_TUNING_PARAM_TASK_INFO_PRIMARY);
    }

    @Override
    public TuningParamTaskInfo as(String alias) {
        return new TuningParamTaskInfo(DSL.name(alias), this);
    }

    @Override
    public TuningParamTaskInfo as(Name alias) {
        return new TuningParamTaskInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TuningParamTaskInfo rename(String name) {
        return new TuningParamTaskInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TuningParamTaskInfo rename(Name name) {
        return new TuningParamTaskInfo(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Integer, String, String, String, String, String, String, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
