/*
 * This file is generated by jOOQ.
 */
package com.alipay.autotuneservice.dao.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 应用管理表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       userId;
    private String        accessToken;
    private String        nodeIds;
    private String        appName;
    private String        appAsName;
    private String        appDesc;
    private LocalDateTime createdTime;
    private LocalDateTime updatedTime;
    private String        status;
    private String        appDefaultJvm;
    private String        clusterName;
    private String        appTag;
    private String        namespace;
    private String        clusterId;

    public AppInfo() {}

    public AppInfo(AppInfo value) {
        this.id = value.id;
        this.userId = value.userId;
        this.accessToken = value.accessToken;
        this.nodeIds = value.nodeIds;
        this.appName = value.appName;
        this.appAsName = value.appAsName;
        this.appDesc = value.appDesc;
        this.createdTime = value.createdTime;
        this.updatedTime = value.updatedTime;
        this.status = value.status;
        this.appDefaultJvm = value.appDefaultJvm;
        this.clusterName = value.clusterName;
        this.appTag = value.appTag;
        this.namespace = value.namespace;
        this.clusterId = value.clusterId;
    }

    public AppInfo(
        Integer       id,
        Integer       userId,
        String        accessToken,
        String        nodeIds,
        String        appName,
        String        appAsName,
        String        appDesc,
        LocalDateTime createdTime,
        LocalDateTime updatedTime,
        String        status,
        String        appDefaultJvm,
        String        clusterName,
        String        appTag,
        String        namespace,
        String        clusterId
    ) {
        this.id = id;
        this.userId = userId;
        this.accessToken = accessToken;
        this.nodeIds = nodeIds;
        this.appName = appName;
        this.appAsName = appAsName;
        this.appDesc = appDesc;
        this.createdTime = createdTime;
        this.updatedTime = updatedTime;
        this.status = status;
        this.appDefaultJvm = appDefaultJvm;
        this.clusterName = clusterName;
        this.appTag = appTag;
        this.namespace = namespace;
        this.clusterId = clusterId;
    }

    /**
     * Getter for <code>tmaestro-lite.app_info.ID</code>. 唯一ID;唯一ID
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>tmaestro-lite.app_info.ID</code>. 唯一ID;唯一ID
     */
    public AppInfo setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.app_info.USER_ID</code>. 关联的用户id
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>tmaestro-lite.app_info.USER_ID</code>. 关联的用户id
     */
    public AppInfo setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.app_info.ACCESS_TOKEN</code>. 关联的token
     */
    public String getAccessToken() {
        return this.accessToken;
    }

    /**
     * Setter for <code>tmaestro-lite.app_info.ACCESS_TOKEN</code>. 关联的token
     */
    public AppInfo setAccessToken(String accessToken) {
        this.accessToken = accessToken;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.app_info.NODE_IDS</code>. 关联的集群组
     */
    public String getNodeIds() {
        return this.nodeIds;
    }

    /**
     * Setter for <code>tmaestro-lite.app_info.NODE_IDS</code>. 关联的集群组
     */
    public AppInfo setNodeIds(String nodeIds) {
        this.nodeIds = nodeIds;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.app_info.APP_NAME</code>. 集群真实名称;集群真实名称
     */
    public String getAppName() {
        return this.appName;
    }

    /**
     * Setter for <code>tmaestro-lite.app_info.APP_NAME</code>. 集群真实名称;集群真实名称
     */
    public AppInfo setAppName(String appName) {
        this.appName = appName;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.app_info.APP_AS_NAME</code>. 应用别名
     */
    public String getAppAsName() {
        return this.appAsName;
    }

    /**
     * Setter for <code>tmaestro-lite.app_info.APP_AS_NAME</code>. 应用别名
     */
    public AppInfo setAppAsName(String appAsName) {
        this.appAsName = appAsName;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.app_info.APP_DESC</code>. 集群说明;集群说明
     */
    public String getAppDesc() {
        return this.appDesc;
    }

    /**
     * Setter for <code>tmaestro-lite.app_info.APP_DESC</code>. 集群说明;集群说明
     */
    public AppInfo setAppDesc(String appDesc) {
        this.appDesc = appDesc;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.app_info.CREATED_TIME</code>. 创建时间;创建时间
     */
    public LocalDateTime getCreatedTime() {
        return this.createdTime;
    }

    /**
     * Setter for <code>tmaestro-lite.app_info.CREATED_TIME</code>. 创建时间;创建时间
     */
    public AppInfo setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.app_info.UPDATED_TIME</code>. 更新时间;更新时间
     */
    public LocalDateTime getUpdatedTime() {
        return this.updatedTime;
    }

    /**
     * Setter for <code>tmaestro-lite.app_info.UPDATED_TIME</code>. 更新时间;更新时间
     */
    public AppInfo setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.app_info.STATUS</code>. 状态;状态
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>tmaestro-lite.app_info.STATUS</code>. 状态;状态
     */
    public AppInfo setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.app_info.APP_DEFAULT_JVM</code>. 集群jvm生效配置;集群jvm生效配置
     */
    public String getAppDefaultJvm() {
        return this.appDefaultJvm;
    }

    /**
     * Setter for <code>tmaestro-lite.app_info.APP_DEFAULT_JVM</code>. 集群jvm生效配置;集群jvm生效配置
     */
    public AppInfo setAppDefaultJvm(String appDefaultJvm) {
        this.appDefaultJvm = appDefaultJvm;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.app_info.CLUSTER_NAME</code>. k8s集群名
     */
    public String getClusterName() {
        return this.clusterName;
    }

    /**
     * Setter for <code>tmaestro-lite.app_info.CLUSTER_NAME</code>. k8s集群名
     */
    public AppInfo setClusterName(String clusterName) {
        this.clusterName = clusterName;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.app_info.app_tag</code>. 标注应用类型
     */
    public String getAppTag() {
        return this.appTag;
    }

    /**
     * Setter for <code>tmaestro-lite.app_info.app_tag</code>. 标注应用类型
     */
    public AppInfo setAppTag(String appTag) {
        this.appTag = appTag;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.app_info.namespace</code>.
     */
    public String getNamespace() {
        return this.namespace;
    }

    /**
     * Setter for <code>tmaestro-lite.app_info.namespace</code>.
     */
    public AppInfo setNamespace(String namespace) {
        this.namespace = namespace;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.app_info.CLUSTER_ID</code>. 集群ID
     */
    public String getClusterId() {
        return this.clusterId;
    }

    /**
     * Setter for <code>tmaestro-lite.app_info.CLUSTER_ID</code>. 集群ID
     */
    public AppInfo setClusterId(String clusterId) {
        this.clusterId = clusterId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AppInfo (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(accessToken);
        sb.append(", ").append(nodeIds);
        sb.append(", ").append(appName);
        sb.append(", ").append(appAsName);
        sb.append(", ").append(appDesc);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(updatedTime);
        sb.append(", ").append(status);
        sb.append(", ").append(appDefaultJvm);
        sb.append(", ").append(clusterName);
        sb.append(", ").append(appTag);
        sb.append(", ").append(namespace);
        sb.append(", ").append(clusterId);

        sb.append(")");
        return sb.toString();
    }
}
