/*
 * This file is generated by jOOQ.
 */
package com.alipay.autotuneservice.dao.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 专家经验
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExpertKnowledge implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        garbageCollector;
    private String        jdkVersion;
    private String        desc;
    private String        problemTypeSet;
    private String        expertJvmPlans;
    private LocalDateTime createdTime;
    private String        createdBy;
    private LocalDateTime updatedTime;

    public ExpertKnowledge() {}

    public ExpertKnowledge(ExpertKnowledge value) {
        this.id = value.id;
        this.garbageCollector = value.garbageCollector;
        this.jdkVersion = value.jdkVersion;
        this.desc = value.desc;
        this.problemTypeSet = value.problemTypeSet;
        this.expertJvmPlans = value.expertJvmPlans;
        this.createdTime = value.createdTime;
        this.createdBy = value.createdBy;
        this.updatedTime = value.updatedTime;
    }

    public ExpertKnowledge(
        Integer       id,
        String        garbageCollector,
        String        jdkVersion,
        String        desc,
        String        problemTypeSet,
        String        expertJvmPlans,
        LocalDateTime createdTime,
        String        createdBy,
        LocalDateTime updatedTime
    ) {
        this.id = id;
        this.garbageCollector = garbageCollector;
        this.jdkVersion = jdkVersion;
        this.desc = desc;
        this.problemTypeSet = problemTypeSet;
        this.expertJvmPlans = expertJvmPlans;
        this.createdTime = createdTime;
        this.createdBy = createdBy;
        this.updatedTime = updatedTime;
    }

    /**
     * Getter for <code>tmaestro-lite.expert_knowledge.ID</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>tmaestro-lite.expert_knowledge.ID</code>.
     */
    public ExpertKnowledge setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.expert_knowledge.GARBAGE_COLLECTOR</code>. 垃圾回收器种类
     */
    public String getGarbageCollector() {
        return this.garbageCollector;
    }

    /**
     * Setter for <code>tmaestro-lite.expert_knowledge.GARBAGE_COLLECTOR</code>. 垃圾回收器种类
     */
    public ExpertKnowledge setGarbageCollector(String garbageCollector) {
        this.garbageCollector = garbageCollector;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.expert_knowledge.JDK_VERSION</code>. jdk版本
     */
    public String getJdkVersion() {
        return this.jdkVersion;
    }

    /**
     * Setter for <code>tmaestro-lite.expert_knowledge.JDK_VERSION</code>. jdk版本
     */
    public ExpertKnowledge setJdkVersion(String jdkVersion) {
        this.jdkVersion = jdkVersion;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.expert_knowledge.DESC</code>. 问题描述
     */
    public String getDesc() {
        return this.desc;
    }

    /**
     * Setter for <code>tmaestro-lite.expert_knowledge.DESC</code>. 问题描述
     */
    public ExpertKnowledge setDesc(String desc) {
        this.desc = desc;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.expert_knowledge.PROBLEM_TYPE_SET</code>. 问题类型集合
     */
    public String getProblemTypeSet() {
        return this.problemTypeSet;
    }

    /**
     * Setter for <code>tmaestro-lite.expert_knowledge.PROBLEM_TYPE_SET</code>. 问题类型集合
     */
    public ExpertKnowledge setProblemTypeSet(String problemTypeSet) {
        this.problemTypeSet = problemTypeSet;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.expert_knowledge.EXPERT_JVM_PLANS</code>. 调整方案
     */
    public String getExpertJvmPlans() {
        return this.expertJvmPlans;
    }

    /**
     * Setter for <code>tmaestro-lite.expert_knowledge.EXPERT_JVM_PLANS</code>. 调整方案
     */
    public ExpertKnowledge setExpertJvmPlans(String expertJvmPlans) {
        this.expertJvmPlans = expertJvmPlans;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.expert_knowledge.CREATED_TIME</code>. 创建时间
     */
    public LocalDateTime getCreatedTime() {
        return this.createdTime;
    }

    /**
     * Setter for <code>tmaestro-lite.expert_knowledge.CREATED_TIME</code>. 创建时间
     */
    public ExpertKnowledge setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.expert_knowledge.CREATED_BY</code>. 创建人
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>tmaestro-lite.expert_knowledge.CREATED_BY</code>. 创建人
     */
    public ExpertKnowledge setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.expert_knowledge.UPDATED_TIME</code>. 更新时间
     */
    public LocalDateTime getUpdatedTime() {
        return this.updatedTime;
    }

    /**
     * Setter for <code>tmaestro-lite.expert_knowledge.UPDATED_TIME</code>. 更新时间
     */
    public ExpertKnowledge setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ExpertKnowledge (");

        sb.append(id);
        sb.append(", ").append(garbageCollector);
        sb.append(", ").append(jdkVersion);
        sb.append(", ").append(desc);
        sb.append(", ").append(problemTypeSet);
        sb.append(", ").append(expertJvmPlans);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(updatedTime);

        sb.append(")");
        return sb.toString();
    }
}
