/*
 * This file is generated by jOOQ.
 */
package com.alipay.autotuneservice.dao.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HealthCheckInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        accessToken;
    private Integer       appId;
    private String        createdBy;
    private LocalDateTime createdTime;
    private String        status;
    private String        probleamPoint;
    private String        grade;
    private String        enchangePoint;
    private String        algoProbleam;

    public HealthCheckInfo() {}

    public HealthCheckInfo(HealthCheckInfo value) {
        this.id = value.id;
        this.accessToken = value.accessToken;
        this.appId = value.appId;
        this.createdBy = value.createdBy;
        this.createdTime = value.createdTime;
        this.status = value.status;
        this.probleamPoint = value.probleamPoint;
        this.grade = value.grade;
        this.enchangePoint = value.enchangePoint;
        this.algoProbleam = value.algoProbleam;
    }

    public HealthCheckInfo(
        Integer       id,
        String        accessToken,
        Integer       appId,
        String        createdBy,
        LocalDateTime createdTime,
        String        status,
        String        probleamPoint,
        String        grade,
        String        enchangePoint,
        String        algoProbleam
    ) {
        this.id = id;
        this.accessToken = accessToken;
        this.appId = appId;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.status = status;
        this.probleamPoint = probleamPoint;
        this.grade = grade;
        this.enchangePoint = enchangePoint;
        this.algoProbleam = algoProbleam;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.HEALTH_CHECK_INFO.ID</code>. 主键ID
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.HEALTH_CHECK_INFO.ID</code>. 主键ID
     */
    public HealthCheckInfo setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.HEALTH_CHECK_INFO.ACCESS_TOKEN</code>. 关联的token
     */
    public String getAccessToken() {
        return this.accessToken;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.HEALTH_CHECK_INFO.ACCESS_TOKEN</code>. 关联的token
     */
    public HealthCheckInfo setAccessToken(String accessToken) {
        this.accessToken = accessToken;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.HEALTH_CHECK_INFO.APP_ID</code>. 关联的集群id
     */
    public Integer getAppId() {
        return this.appId;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.HEALTH_CHECK_INFO.APP_ID</code>. 关联的集群id
     */
    public HealthCheckInfo setAppId(Integer appId) {
        this.appId = appId;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.HEALTH_CHECK_INFO.CREATED_BY</code>. 创建人
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.HEALTH_CHECK_INFO.CREATED_BY</code>. 创建人
     */
    public HealthCheckInfo setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.HEALTH_CHECK_INFO.CREATED_TIME</code>. 创建时间
     */
    public LocalDateTime getCreatedTime() {
        return this.createdTime;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.HEALTH_CHECK_INFO.CREATED_TIME</code>. 创建时间
     */
    public HealthCheckInfo setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.HEALTH_CHECK_INFO.STATUS</code>. 状态:检查成功、检查失败
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.HEALTH_CHECK_INFO.STATUS</code>. 状态:检查成功、检查失败
     */
    public HealthCheckInfo setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.HEALTH_CHECK_INFO.PROBLEAM_POINT</code>. 检查问题点
     */
    public String getProbleamPoint() {
        return this.probleamPoint;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.HEALTH_CHECK_INFO.PROBLEAM_POINT</code>. 检查问题点
     */
    public HealthCheckInfo setProbleamPoint(String probleamPoint) {
        this.probleamPoint = probleamPoint;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.HEALTH_CHECK_INFO.GRADE</code>. 分数
     */
    public String getGrade() {
        return this.grade;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.HEALTH_CHECK_INFO.GRADE</code>. 分数
     */
    public HealthCheckInfo setGrade(String grade) {
        this.grade = grade;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.HEALTH_CHECK_INFO.ENCHANGE_POINT</code>. 改变的点
     */
    public String getEnchangePoint() {
        return this.enchangePoint;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.HEALTH_CHECK_INFO.ENCHANGE_POINT</code>. 改变的点
     */
    public HealthCheckInfo setEnchangePoint(String enchangePoint) {
        this.enchangePoint = enchangePoint;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.HEALTH_CHECK_INFO.ALGO_PROBLEAM</code>.
     */
    public String getAlgoProbleam() {
        return this.algoProbleam;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.HEALTH_CHECK_INFO.ALGO_PROBLEAM</code>.
     */
    public HealthCheckInfo setAlgoProbleam(String algoProbleam) {
        this.algoProbleam = algoProbleam;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("HealthCheckInfo (");

        sb.append(id);
        sb.append(", ").append(accessToken);
        sb.append(", ").append(appId);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(status);
        sb.append(", ").append(probleamPoint);
        sb.append(", ").append(grade);
        sb.append(", ").append(enchangePoint);
        sb.append(", ").append(algoProbleam);

        sb.append(")");
        return sb.toString();
    }
}
