/*
 * This file is generated by jOOQ.
 */
package com.alipay.autotuneservice.dao.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JavaInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       pid;
    private String        version;
    private String        jvmHome;
    private String        classPath;
    private String        libraryPath;
    private String        userName;
    private String        userDir;
    private String        execTime;
    private String        javaLibs;
    private String        inputArguments;
    private String        hostName;
    private String        osVersion;
    private String        osArch;
    private String        appName;
    private String        namespace;
    private LocalDateTime createdTime;
    private LocalDateTime updatedTime;

    public JavaInfo() {}

    public JavaInfo(JavaInfo value) {
        this.id = value.id;
        this.pid = value.pid;
        this.version = value.version;
        this.jvmHome = value.jvmHome;
        this.classPath = value.classPath;
        this.libraryPath = value.libraryPath;
        this.userName = value.userName;
        this.userDir = value.userDir;
        this.execTime = value.execTime;
        this.javaLibs = value.javaLibs;
        this.inputArguments = value.inputArguments;
        this.hostName = value.hostName;
        this.osVersion = value.osVersion;
        this.osArch = value.osArch;
        this.appName = value.appName;
        this.namespace = value.namespace;
        this.createdTime = value.createdTime;
        this.updatedTime = value.updatedTime;
    }

    public JavaInfo(
        Integer       id,
        Integer       pid,
        String        version,
        String        jvmHome,
        String        classPath,
        String        libraryPath,
        String        userName,
        String        userDir,
        String        execTime,
        String        javaLibs,
        String        inputArguments,
        String        hostName,
        String        osVersion,
        String        osArch,
        String        appName,
        String        namespace,
        LocalDateTime createdTime,
        LocalDateTime updatedTime
    ) {
        this.id = id;
        this.pid = pid;
        this.version = version;
        this.jvmHome = jvmHome;
        this.classPath = classPath;
        this.libraryPath = libraryPath;
        this.userName = userName;
        this.userDir = userDir;
        this.execTime = execTime;
        this.javaLibs = javaLibs;
        this.inputArguments = inputArguments;
        this.hostName = hostName;
        this.osVersion = osVersion;
        this.osArch = osArch;
        this.appName = appName;
        this.namespace = namespace;
        this.createdTime = createdTime;
        this.updatedTime = updatedTime;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JAVA_INFO.ID</code>. 唯一ID;唯一ID
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JAVA_INFO.ID</code>. 唯一ID;唯一ID
     */
    public JavaInfo setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JAVA_INFO.PID</code>. 应用id
     */
    public Integer getPid() {
        return this.pid;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JAVA_INFO.PID</code>. 应用id
     */
    public JavaInfo setPid(Integer pid) {
        this.pid = pid;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JAVA_INFO.VERSION</code>. 版本
     */
    public String getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JAVA_INFO.VERSION</code>. 版本
     */
    public JavaInfo setVersion(String version) {
        this.version = version;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JAVA_INFO.JVM_HOME</code>. javaHome
     */
    public String getJvmHome() {
        return this.jvmHome;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JAVA_INFO.JVM_HOME</code>. javaHome
     */
    public JavaInfo setJvmHome(String jvmHome) {
        this.jvmHome = jvmHome;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JAVA_INFO.CLASS_PATH</code>. classPath
     */
    public String getClassPath() {
        return this.classPath;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JAVA_INFO.CLASS_PATH</code>. classPath
     */
    public JavaInfo setClassPath(String classPath) {
        this.classPath = classPath;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JAVA_INFO.LIBRARY_PATH</code>. 文件路径
     */
    public String getLibraryPath() {
        return this.libraryPath;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JAVA_INFO.LIBRARY_PATH</code>. 文件路径
     */
    public JavaInfo setLibraryPath(String libraryPath) {
        this.libraryPath = libraryPath;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JAVA_INFO.USER_NAME</code>. userName
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JAVA_INFO.USER_NAME</code>. userName
     */
    public JavaInfo setUserName(String userName) {
        this.userName = userName;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JAVA_INFO.USER_DIR</code>. userDir
     */
    public String getUserDir() {
        return this.userDir;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JAVA_INFO.USER_DIR</code>. userDir
     */
    public JavaInfo setUserDir(String userDir) {
        this.userDir = userDir;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JAVA_INFO.EXEC_TIME</code>. 存活时间
     */
    public String getExecTime() {
        return this.execTime;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JAVA_INFO.EXEC_TIME</code>. 存活时间
     */
    public JavaInfo setExecTime(String execTime) {
        this.execTime = execTime;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JAVA_INFO.JAVA_LIBS</code>. 依赖包
     */
    public String getJavaLibs() {
        return this.javaLibs;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JAVA_INFO.JAVA_LIBS</code>. 依赖包
     */
    public JavaInfo setJavaLibs(String javaLibs) {
        this.javaLibs = javaLibs;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JAVA_INFO.INPUT_ARGUMENTS</code>. 启动参数
     */
    public String getInputArguments() {
        return this.inputArguments;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JAVA_INFO.INPUT_ARGUMENTS</code>. 启动参数
     */
    public JavaInfo setInputArguments(String inputArguments) {
        this.inputArguments = inputArguments;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JAVA_INFO.HOST_NAME</code>. hostname
     */
    public String getHostName() {
        return this.hostName;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JAVA_INFO.HOST_NAME</code>. hostname
     */
    public JavaInfo setHostName(String hostName) {
        this.hostName = hostName;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JAVA_INFO.OS_VERSION</code>. osVersion
     */
    public String getOsVersion() {
        return this.osVersion;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JAVA_INFO.OS_VERSION</code>. osVersion
     */
    public JavaInfo setOsVersion(String osVersion) {
        this.osVersion = osVersion;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JAVA_INFO.OS_ARCH</code>. osArch
     */
    public String getOsArch() {
        return this.osArch;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JAVA_INFO.OS_ARCH</code>. osArch
     */
    public JavaInfo setOsArch(String osArch) {
        this.osArch = osArch;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JAVA_INFO.APP_NAME</code>. 集群真实名称;集群真实名称
     */
    public String getAppName() {
        return this.appName;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JAVA_INFO.APP_NAME</code>. 集群真实名称;集群真实名称
     */
    public JavaInfo setAppName(String appName) {
        this.appName = appName;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JAVA_INFO.NAMESPACE</code>.
     */
    public String getNamespace() {
        return this.namespace;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JAVA_INFO.NAMESPACE</code>.
     */
    public JavaInfo setNamespace(String namespace) {
        this.namespace = namespace;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JAVA_INFO.CREATED_TIME</code>. 创建时间;创建时间
     */
    public LocalDateTime getCreatedTime() {
        return this.createdTime;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JAVA_INFO.CREATED_TIME</code>. 创建时间;创建时间
     */
    public JavaInfo setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JAVA_INFO.UPDATED_TIME</code>. 更新时间;更新时间
     */
    public LocalDateTime getUpdatedTime() {
        return this.updatedTime;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JAVA_INFO.UPDATED_TIME</code>. 更新时间;更新时间
     */
    public JavaInfo setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JavaInfo (");

        sb.append(id);
        sb.append(", ").append(pid);
        sb.append(", ").append(version);
        sb.append(", ").append(jvmHome);
        sb.append(", ").append(classPath);
        sb.append(", ").append(libraryPath);
        sb.append(", ").append(userName);
        sb.append(", ").append(userDir);
        sb.append(", ").append(execTime);
        sb.append(", ").append(javaLibs);
        sb.append(", ").append(inputArguments);
        sb.append(", ").append(hostName);
        sb.append(", ").append(osVersion);
        sb.append(", ").append(osArch);
        sb.append(", ").append(appName);
        sb.append(", ").append(namespace);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(updatedTime);

        sb.append(")");
        return sb.toString();
    }
}
