/*
 * This file is generated by jOOQ.
 */
package com.alipay.autotuneservice.dao.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JvmMonitorMetricData implements Serializable {

    private static final long serialVersionUID = 1L;

    private String podName;
    private Long   gmtModified;
    private String appName;
    private String data;

    public JvmMonitorMetricData() {}

    public JvmMonitorMetricData(JvmMonitorMetricData value) {
        this.podName = value.podName;
        this.gmtModified = value.gmtModified;
        this.appName = value.appName;
        this.data = value.data;
    }

    public JvmMonitorMetricData(
        String podName,
        Long   gmtModified,
        String appName,
        String data
    ) {
        this.podName = podName;
        this.gmtModified = gmtModified;
        this.appName = appName;
        this.data = data;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JVM_MONITOR_METRIC_DATA.POD_NAME</code>. pod name
     */
    public String getPodName() {
        return this.podName;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JVM_MONITOR_METRIC_DATA.POD_NAME</code>. pod name
     */
    public JvmMonitorMetricData setPodName(String podName) {
        this.podName = podName;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JVM_MONITOR_METRIC_DATA.GMT_MODIFIED</code>. 修改时间
     */
    public Long getGmtModified() {
        return this.gmtModified;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JVM_MONITOR_METRIC_DATA.GMT_MODIFIED</code>. 修改时间
     */
    public JvmMonitorMetricData setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JVM_MONITOR_METRIC_DATA.APP_NAME</code>. app name
     */
    public String getAppName() {
        return this.appName;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JVM_MONITOR_METRIC_DATA.APP_NAME</code>. app name
     */
    public JvmMonitorMetricData setAppName(String appName) {
        this.appName = appName;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.JVM_MONITOR_METRIC_DATA.DATA</code>.
     */
    public String getData() {
        return this.data;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.JVM_MONITOR_METRIC_DATA.DATA</code>.
     */
    public JvmMonitorMetricData setData(String data) {
        this.data = data;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JvmMonitorMetricData (");

        sb.append(podName);
        sb.append(", ").append(gmtModified);
        sb.append(", ").append(appName);
        sb.append(", ").append(data);

        sb.append(")");
        return sb.toString();
    }
}
