/*
 * This file is generated by jOOQ.
 */
package com.alipay.autotuneservice.dao.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JvmOptsConfig implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        jvmOpt;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;

    public JvmOptsConfig() {}

    public JvmOptsConfig(JvmOptsConfig value) {
        this.id = value.id;
        this.jvmOpt = value.jvmOpt;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public JvmOptsConfig(
        Long          id,
        String        jvmOpt,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.id = id;
        this.jvmOpt = jvmOpt;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>tmaestro-lite.jvm_opts_config.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>tmaestro-lite.jvm_opts_config.id</code>.
     */
    public JvmOptsConfig setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.jvm_opts_config.jvm_opt</code>.
     */
    public String getJvmOpt() {
        return this.jvmOpt;
    }

    /**
     * Setter for <code>tmaestro-lite.jvm_opts_config.jvm_opt</code>.
     */
    public JvmOptsConfig setJvmOpt(String jvmOpt) {
        this.jvmOpt = jvmOpt;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.jvm_opts_config.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>tmaestro-lite.jvm_opts_config.create_time</code>.
     */
    public JvmOptsConfig setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.jvm_opts_config.update_time</code>.
     */
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>tmaestro-lite.jvm_opts_config.update_time</code>.
     */
    public JvmOptsConfig setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JvmOptsConfig (");

        sb.append(id);
        sb.append(", ").append(jvmOpt);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
