/*
 * This file is generated by jOOQ.
 */
package com.alipay.autotuneservice.dao.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RiskStatisticPreData implements Serializable {

    private static final long serialVersionUID = 1L;

    private String podName;
    private Long   appId;
    private String dt;
    private Long   timeStamp;
    private String data;

    public RiskStatisticPreData() {}

    public RiskStatisticPreData(RiskStatisticPreData value) {
        this.podName = value.podName;
        this.appId = value.appId;
        this.dt = value.dt;
        this.timeStamp = value.timeStamp;
        this.data = value.data;
    }

    public RiskStatisticPreData(
        String podName,
        Long   appId,
        String dt,
        Long   timeStamp,
        String data
    ) {
        this.podName = podName;
        this.appId = appId;
        this.dt = dt;
        this.timeStamp = timeStamp;
        this.data = data;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.RISK_STATISTIC_PRE_DATA.POD_NAME</code>. pod name
     */
    public String getPodName() {
        return this.podName;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.RISK_STATISTIC_PRE_DATA.POD_NAME</code>. pod name
     */
    public RiskStatisticPreData setPodName(String podName) {
        this.podName = podName;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.RISK_STATISTIC_PRE_DATA.APP_ID</code>. app id
     */
    public Long getAppId() {
        return this.appId;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.RISK_STATISTIC_PRE_DATA.APP_ID</code>. app id
     */
    public RiskStatisticPreData setAppId(Long appId) {
        this.appId = appId;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.RISK_STATISTIC_PRE_DATA.DT</code>. 天分区
     */
    public String getDt() {
        return this.dt;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.RISK_STATISTIC_PRE_DATA.DT</code>. 天分区
     */
    public RiskStatisticPreData setDt(String dt) {
        this.dt = dt;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.RISK_STATISTIC_PRE_DATA.TIME_STAMP</code>. 时间戳
     */
    public Long getTimeStamp() {
        return this.timeStamp;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.RISK_STATISTIC_PRE_DATA.TIME_STAMP</code>. 时间戳
     */
    public RiskStatisticPreData setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.RISK_STATISTIC_PRE_DATA.DATA</code>.
     */
    public String getData() {
        return this.data;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.RISK_STATISTIC_PRE_DATA.DATA</code>.
     */
    public RiskStatisticPreData setData(String data) {
        this.data = data;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RiskStatisticPreData (");

        sb.append(podName);
        sb.append(", ").append(appId);
        sb.append(", ").append(dt);
        sb.append(", ").append(timeStamp);
        sb.append(", ").append(data);

        sb.append(")");
        return sb.toString();
    }
}
