/*
 * This file is generated by jOOQ.
 */
package com.alipay.autotuneservice.dao.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * s3永久文件存储卷
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StorageInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private String        s3Key;
    private String        fileName;
    private LocalDateTime createdTime;
    private LocalDateTime updatedTime;

    public StorageInfo() {}

    public StorageInfo(StorageInfo value) {
        this.id = value.id;
        this.s3Key = value.s3Key;
        this.fileName = value.fileName;
        this.createdTime = value.createdTime;
        this.updatedTime = value.updatedTime;
    }

    public StorageInfo(
        Long          id,
        String        s3Key,
        String        fileName,
        LocalDateTime createdTime,
        LocalDateTime updatedTime
    ) {
        this.id = id;
        this.s3Key = s3Key;
        this.fileName = fileName;
        this.createdTime = createdTime;
        this.updatedTime = updatedTime;
    }

    /**
     * Getter for <code>tmaestro-lite.storage_info.ID</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>tmaestro-lite.storage_info.ID</code>.
     */
    public StorageInfo setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.storage_info.S3_KEY</code>.
     */
    public String getS3Key() {
        return this.s3Key;
    }

    /**
     * Setter for <code>tmaestro-lite.storage_info.S3_KEY</code>.
     */
    public StorageInfo setS3Key(String s3Key) {
        this.s3Key = s3Key;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.storage_info.FILE_NAME</code>.
     */
    public String getFileName() {
        return this.fileName;
    }

    /**
     * Setter for <code>tmaestro-lite.storage_info.FILE_NAME</code>.
     */
    public StorageInfo setFileName(String fileName) {
        this.fileName = fileName;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.storage_info.CREATED_TIME</code>.
     */
    public LocalDateTime getCreatedTime() {
        return this.createdTime;
    }

    /**
     * Setter for <code>tmaestro-lite.storage_info.CREATED_TIME</code>.
     */
    public StorageInfo setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
        return this;
    }

    /**
     * Getter for <code>tmaestro-lite.storage_info.UPDATED_TIME</code>.
     */
    public LocalDateTime getUpdatedTime() {
        return this.updatedTime;
    }

    /**
     * Setter for <code>tmaestro-lite.storage_info.UPDATED_TIME</code>.
     */
    public StorageInfo setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StorageInfo (");

        sb.append(id);
        sb.append(", ").append(s3Key);
        sb.append(", ").append(fileName);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(updatedTime);

        sb.append(")");
        return sb.toString();
    }
}
