/*
 * This file is generated by jOOQ.
 */
package com.alipay.autotuneservice.dao.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TuneParamInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private LocalDateTime createTime;
    private LocalDateTime updatedTime;
    private Integer       appId;
    private Integer       pipelineId;
    private Integer       jvmMarketId;
    private String        decisionId;
    private String        updateStatus;
    private String        accessToken;
    private String        updateParams;
    private String        operator;
    private String        changedTuneGroup;
    private String        defaultParam;
    private Integer       version;

    public TuneParamInfo() {}

    public TuneParamInfo(TuneParamInfo value) {
        this.id = value.id;
        this.createTime = value.createTime;
        this.updatedTime = value.updatedTime;
        this.appId = value.appId;
        this.pipelineId = value.pipelineId;
        this.jvmMarketId = value.jvmMarketId;
        this.decisionId = value.decisionId;
        this.updateStatus = value.updateStatus;
        this.accessToken = value.accessToken;
        this.updateParams = value.updateParams;
        this.operator = value.operator;
        this.changedTuneGroup = value.changedTuneGroup;
        this.defaultParam = value.defaultParam;
        this.version = value.version;
    }

    public TuneParamInfo(
        Integer       id,
        LocalDateTime createTime,
        LocalDateTime updatedTime,
        Integer       appId,
        Integer       pipelineId,
        Integer       jvmMarketId,
        String        decisionId,
        String        updateStatus,
        String        accessToken,
        String        updateParams,
        String        operator,
        String        changedTuneGroup,
        String        defaultParam,
        Integer       version
    ) {
        this.id = id;
        this.createTime = createTime;
        this.updatedTime = updatedTime;
        this.appId = appId;
        this.pipelineId = pipelineId;
        this.jvmMarketId = jvmMarketId;
        this.decisionId = decisionId;
        this.updateStatus = updateStatus;
        this.accessToken = accessToken;
        this.updateParams = updateParams;
        this.operator = operator;
        this.changedTuneGroup = changedTuneGroup;
        this.defaultParam = defaultParam;
        this.version = version;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.ID</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.ID</code>.
     */
    public TuneParamInfo setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.CREATE_TIME</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.CREATE_TIME</code>. 创建时间
     */
    public TuneParamInfo setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.UPDATED_TIME</code>. 更新时间
     */
    public LocalDateTime getUpdatedTime() {
        return this.updatedTime;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.UPDATED_TIME</code>. 更新时间
     */
    public TuneParamInfo setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.APP_ID</code>. app id
     */
    public Integer getAppId() {
        return this.appId;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.APP_ID</code>. app id
     */
    public TuneParamInfo setAppId(Integer appId) {
        this.appId = appId;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.PIPELINE_ID</code>. pipeline id
     */
    public Integer getPipelineId() {
        return this.pipelineId;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.PIPELINE_ID</code>. pipeline id
     */
    public TuneParamInfo setPipelineId(Integer pipelineId) {
        this.pipelineId = pipelineId;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.JVM_MARKET_ID</code>. jvm market id
     */
    public Integer getJvmMarketId() {
        return this.jvmMarketId;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.JVM_MARKET_ID</code>. jvm market id
     */
    public TuneParamInfo setJvmMarketId(Integer jvmMarketId) {
        this.jvmMarketId = jvmMarketId;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.DECISION_ID</code>. decision Id
     */
    public String getDecisionId() {
        return this.decisionId;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.DECISION_ID</code>. decision Id
     */
    public TuneParamInfo setDecisionId(String decisionId) {
        this.decisionId = decisionId;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.UPDATE_STATUS</code>. 更新参数的状态
     */
    public String getUpdateStatus() {
        return this.updateStatus;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.UPDATE_STATUS</code>. 更新参数的状态
     */
    public TuneParamInfo setUpdateStatus(String updateStatus) {
        this.updateStatus = updateStatus;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.ACCESS_TOKEN</code>. acess token
     */
    public String getAccessToken() {
        return this.accessToken;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.ACCESS_TOKEN</code>. acess token
     */
    public TuneParamInfo setAccessToken(String accessToken) {
        this.accessToken = accessToken;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.UPDATE_PARAMS</code>. 更新的JVM参数，以JSON形式存储
     */
    public String getUpdateParams() {
        return this.updateParams;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.UPDATE_PARAMS</code>. 更新的JVM参数，以JSON形式存储
     */
    public TuneParamInfo setUpdateParams(String updateParams) {
        this.updateParams = updateParams;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.OPERATOR</code>. 操作员
     */
    public String getOperator() {
        return this.operator;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.OPERATOR</code>. 操作员
     */
    public TuneParamInfo setOperator(String operator) {
        this.operator = operator;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.CHANGED_TUNE_GROUP</code>. 修改的调参分组信息，json形式
     */
    public String getChangedTuneGroup() {
        return this.changedTuneGroup;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.CHANGED_TUNE_GROUP</code>. 修改的调参分组信息，json形式
     */
    public TuneParamInfo setChangedTuneGroup(String changedTuneGroup) {
        this.changedTuneGroup = changedTuneGroup;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.DEFAULT_PARAM</code>. app默认启动参数
     */
    public String getDefaultParam() {
        return this.defaultParam;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.DEFAULT_PARAM</code>. app默认启动参数
     */
    public TuneParamInfo setDefaultParam(String defaultParam) {
        this.defaultParam = defaultParam;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.VERSION</code>.
     */
    public Integer getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TUNE_PARAM_INFO.VERSION</code>.
     */
    public TuneParamInfo setVersion(Integer version) {
        this.version = version;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TuneParamInfo (");

        sb.append(id);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updatedTime);
        sb.append(", ").append(appId);
        sb.append(", ").append(pipelineId);
        sb.append(", ").append(jvmMarketId);
        sb.append(", ").append(decisionId);
        sb.append(", ").append(updateStatus);
        sb.append(", ").append(accessToken);
        sb.append(", ").append(updateParams);
        sb.append(", ").append(operator);
        sb.append(", ").append(changedTuneGroup);
        sb.append(", ").append(defaultParam);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
