/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * This file is generated by jOOQ.
 */
package com.alipay.autotuneservice.dao.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TwatchInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private String containerId;
    private String containerName;
    private String namespace;
    private String podName;
    private String agentName;
    private Long   gmtModified;
    private Long   dtPeriod;
    private String nodeName;
    private String nodeIp;

    public TwatchInfo() {}

    public TwatchInfo(TwatchInfo value) {
        this.containerId = value.containerId;
        this.containerName = value.containerName;
        this.namespace = value.namespace;
        this.podName = value.podName;
        this.agentName = value.agentName;
        this.gmtModified = value.gmtModified;
        this.dtPeriod = value.dtPeriod;
        this.nodeName = value.nodeName;
        this.nodeIp = value.nodeIp;
    }

    public TwatchInfo(
        String containerId,
        String containerName,
        String namespace,
        String podName,
        String agentName,
        Long   gmtModified,
        Long   dtPeriod,
        String nodeName,
        String nodeIp
    ) {
        this.containerId = containerId;
        this.containerName = containerName;
        this.namespace = namespace;
        this.podName = podName;
        this.agentName = agentName;
        this.gmtModified = gmtModified;
        this.dtPeriod = dtPeriod;
        this.nodeName = nodeName;
        this.nodeIp = nodeIp;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TWATCH_INFO.CONTAINER_ID</code>. cantainer Id
     */
    public String getContainerId() {
        return this.containerId;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TWATCH_INFO.CONTAINER_ID</code>. cantainer Id
     */
    public TwatchInfo setContainerId(String containerId) {
        this.containerId = containerId;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TWATCH_INFO.CONTAINER_NAME</code>. 容器名称
     */
    public String getContainerName() {
        return this.containerName;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TWATCH_INFO.CONTAINER_NAME</code>. 容器名称
     */
    public TwatchInfo setContainerName(String containerName) {
        this.containerName = containerName;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TWATCH_INFO.NAMESPACE</code>. 容器所在namespace
     */
    public String getNamespace() {
        return this.namespace;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TWATCH_INFO.NAMESPACE</code>. 容器所在namespace
     */
    public TwatchInfo setNamespace(String namespace) {
        this.namespace = namespace;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TWATCH_INFO.POD_NAME</code>. pod name
     */
    public String getPodName() {
        return this.podName;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TWATCH_INFO.POD_NAME</code>. pod name
     */
    public TwatchInfo setPodName(String podName) {
        this.podName = podName;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TWATCH_INFO.AGENT_NAME</code>. twatch demonset pod name
     */
    public String getAgentName() {
        return this.agentName;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TWATCH_INFO.AGENT_NAME</code>. twatch demonset pod name
     */
    public TwatchInfo setAgentName(String agentName) {
        this.agentName = agentName;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TWATCH_INFO.GMT_MODIFIED</code>. 修改时间
     */
    public Long getGmtModified() {
        return this.gmtModified;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TWATCH_INFO.GMT_MODIFIED</code>. 修改时间
     */
    public TwatchInfo setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TWATCH_INFO.DT_PERIOD</code>. 按天分区
     */
    public Long getDtPeriod() {
        return this.dtPeriod;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TWATCH_INFO.DT_PERIOD</code>. 按天分区
     */
    public TwatchInfo setDtPeriod(Long dtPeriod) {
        this.dtPeriod = dtPeriod;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TWATCH_INFO.NODE_NAME</code>. node name
     */
    public String getNodeName() {
        return this.nodeName;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TWATCH_INFO.NODE_NAME</code>. node name
     */
    public TwatchInfo setNodeName(String nodeName) {
        this.nodeName = nodeName;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TWATCH_INFO.NODE_IP</code>. node ip
     */
    public String getNodeIp() {
        return this.nodeIp;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TWATCH_INFO.NODE_IP</code>. node ip
     */
    public TwatchInfo setNodeIp(String nodeIp) {
        this.nodeIp = nodeIp;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TwatchInfo (");

        sb.append(containerId);
        sb.append(", ").append(containerName);
        sb.append(", ").append(namespace);
        sb.append(", ").append(podName);
        sb.append(", ").append(agentName);
        sb.append(", ").append(gmtModified);
        sb.append(", ").append(dtPeriod);
        sb.append(", ").append(nodeName);
        sb.append(", ").append(nodeIp);

        sb.append(")");
        return sb.toString();
    }
}
