/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * This file is generated by jOOQ.
 */
package com.alipay.autotuneservice.dao.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        accountId;
    private String        accessToken;
    private String        userCompany;
    private String        userName;
    private LocalDateTime createdTime;
    private LocalDateTime updatedTime;
    private String        tenantCode;
    private String        productAccountId;
    private String        planCode;

    public UserInfo() {}

    public UserInfo(UserInfo value) {
        this.id = value.id;
        this.accountId = value.accountId;
        this.accessToken = value.accessToken;
        this.userCompany = value.userCompany;
        this.userName = value.userName;
        this.createdTime = value.createdTime;
        this.updatedTime = value.updatedTime;
        this.tenantCode = value.tenantCode;
        this.productAccountId = value.productAccountId;
        this.planCode = value.planCode;
    }

    public UserInfo(
        Integer       id,
        String        accountId,
        String        accessToken,
        String        userCompany,
        String        userName,
        LocalDateTime createdTime,
        LocalDateTime updatedTime,
        String        tenantCode,
        String        productAccountId,
        String        planCode
    ) {
        this.id = id;
        this.accountId = accountId;
        this.accessToken = accessToken;
        this.userCompany = userCompany;
        this.userName = userName;
        this.createdTime = createdTime;
        this.updatedTime = updatedTime;
        this.tenantCode = tenantCode;
        this.productAccountId = productAccountId;
        this.planCode = planCode;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.USER_INFO.ID</code>. 主键ID
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.USER_INFO.ID</code>. 主键ID
     */
    public UserInfo setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.USER_INFO.ACCOUNT_ID</code>. 关联的AWS用户ID
     */
    public String getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.USER_INFO.ACCOUNT_ID</code>. 关联的AWS用户ID
     */
    public UserInfo setAccountId(String accountId) {
        this.accountId = accountId;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.USER_INFO.ACCESS_TOKEN</code>. 关联的token
     */
    public String getAccessToken() {
        return this.accessToken;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.USER_INFO.ACCESS_TOKEN</code>. 关联的token
     */
    public UserInfo setAccessToken(String accessToken) {
        this.accessToken = accessToken;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.USER_INFO.USER_COMPANY</code>. 所属公司
     */
    public String getUserCompany() {
        return this.userCompany;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.USER_INFO.USER_COMPANY</code>. 所属公司
     */
    public UserInfo setUserCompany(String userCompany) {
        this.userCompany = userCompany;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.USER_INFO.USER_NAME</code>. 名称
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.USER_INFO.USER_NAME</code>. 名称
     */
    public UserInfo setUserName(String userName) {
        this.userName = userName;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.USER_INFO.CREATED_TIME</code>. 创建时间
     */
    public LocalDateTime getCreatedTime() {
        return this.createdTime;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.USER_INFO.CREATED_TIME</code>. 创建时间
     */
    public UserInfo setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.USER_INFO.UPDATED_TIME</code>. 更新时间
     */
    public LocalDateTime getUpdatedTime() {
        return this.updatedTime;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.USER_INFO.UPDATED_TIME</code>. 更新时间
     */
    public UserInfo setUpdatedTime(LocalDateTime updatedTime) {
        this.updatedTime = updatedTime;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.USER_INFO.TENANT_CODE</code>. 租户

     */
    public String getTenantCode() {
        return this.tenantCode;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.USER_INFO.TENANT_CODE</code>. 租户

     */
    public UserInfo setTenantCode(String tenantCode) {
        this.tenantCode = tenantCode;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.USER_INFO.PRODUCT_ACCOUNT_ID</code>. 产品账户
     */
    public String getProductAccountId() {
        return this.productAccountId;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.USER_INFO.PRODUCT_ACCOUNT_ID</code>. 产品账户
     */
    public UserInfo setProductAccountId(String productAccountId) {
        this.productAccountId = productAccountId;
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.USER_INFO.PLAN_CODE</code>.
     */
    public String getPlanCode() {
        return this.planCode;
    }

    /**
     * Setter for <code>TMAESTRO-LITE.USER_INFO.PLAN_CODE</code>.
     */
    public UserInfo setPlanCode(String planCode) {
        this.planCode = planCode;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserInfo (");

        sb.append(id);
        sb.append(", ").append(accountId);
        sb.append(", ").append(accessToken);
        sb.append(", ").append(userCompany);
        sb.append(", ").append(userName);
        sb.append(", ").append(createdTime);
        sb.append(", ").append(updatedTime);
        sb.append(", ").append(tenantCode);
        sb.append(", ").append(productAccountId);
        sb.append(", ").append(planCode);

        sb.append(")");
        return sb.toString();
    }
}
