/*
 * This file is generated by jOOQ.
 */
package com.alipay.autotuneservice.dao.jooq.tables.records;


import com.alipay.autotuneservice.dao.jooq.tables.Alarm;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlarmRecord extends UpdatableRecordImpl<AlarmRecord> implements Record14<Integer, String, String, Integer, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>TMAESTRO-LITE.ALARM.ID</code>.
     */
    public AlarmRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.ALARM.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.ALARM.ALARM_NAME</code>.
     */
    public AlarmRecord setAlarmName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.ALARM.ALARM_NAME</code>.
     */
    public String getAlarmName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.ALARM.APP_NAME</code>.
     */
    public AlarmRecord setAppName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.ALARM.APP_NAME</code>.
     */
    public String getAppName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.ALARM.APP_ID</code>.
     */
    public AlarmRecord setAppId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.ALARM.APP_ID</code>.
     */
    public Integer getAppId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.ALARM.STATUS</code>.
     */
    public AlarmRecord setStatus(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.ALARM.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.ALARM.ALARM_RULE</code>.
     */
    public AlarmRecord setAlarmRule(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.ALARM.ALARM_RULE</code>.
     */
    public String getAlarmRule() {
        return (String) get(5);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.ALARM.RULE_ACTION</code>.
     */
    public AlarmRecord setRuleAction(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.ALARM.RULE_ACTION</code>.
     */
    public String getRuleAction() {
        return (String) get(6);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.ALARM.ALARM_NOTICE</code>.
     */
    public AlarmRecord setAlarmNotice(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.ALARM.ALARM_NOTICE</code>.
     */
    public String getAlarmNotice() {
        return (String) get(7);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.ALARM.CREATE_BY</code>.
     */
    public AlarmRecord setCreateBy(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.ALARM.CREATE_BY</code>.
     */
    public String getCreateBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.ALARM.CONTEXT</code>.
     */
    public AlarmRecord setContext(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.ALARM.CONTEXT</code>.
     */
    public String getContext() {
        return (String) get(9);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.ALARM.CREATED_TIME</code>.
     */
    public AlarmRecord setCreatedTime(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.ALARM.CREATED_TIME</code>.
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.ALARM.UPDATED_TIME</code>.
     */
    public AlarmRecord setUpdatedTime(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.ALARM.UPDATED_TIME</code>.
     */
    public LocalDateTime getUpdatedTime() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.ALARM.COMBINATION_TYPE</code>.
     */
    public AlarmRecord setCombinationType(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.ALARM.COMBINATION_TYPE</code>.
     */
    public String getCombinationType() {
        return (String) get(12);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.ALARM.ACCESS_TOKEN</code>.
     */
    public AlarmRecord setAccessToken(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.ALARM.ACCESS_TOKEN</code>.
     */
    public String getAccessToken() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Integer, String, String, Integer, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Integer, String, String, Integer, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Alarm.ALARM.ID;
    }

    @Override
    public Field<String> field2() {
        return Alarm.ALARM.ALARM_NAME;
    }

    @Override
    public Field<String> field3() {
        return Alarm.ALARM.APP_NAME;
    }

    @Override
    public Field<Integer> field4() {
        return Alarm.ALARM.APP_ID;
    }

    @Override
    public Field<String> field5() {
        return Alarm.ALARM.STATUS;
    }

    @Override
    public Field<String> field6() {
        return Alarm.ALARM.ALARM_RULE;
    }

    @Override
    public Field<String> field7() {
        return Alarm.ALARM.RULE_ACTION;
    }

    @Override
    public Field<String> field8() {
        return Alarm.ALARM.ALARM_NOTICE;
    }

    @Override
    public Field<String> field9() {
        return Alarm.ALARM.CREATE_BY;
    }

    @Override
    public Field<String> field10() {
        return Alarm.ALARM.CONTEXT;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return Alarm.ALARM.CREATED_TIME;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return Alarm.ALARM.UPDATED_TIME;
    }

    @Override
    public Field<String> field13() {
        return Alarm.ALARM.COMBINATION_TYPE;
    }

    @Override
    public Field<String> field14() {
        return Alarm.ALARM.ACCESS_TOKEN;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAlarmName();
    }

    @Override
    public String component3() {
        return getAppName();
    }

    @Override
    public Integer component4() {
        return getAppId();
    }

    @Override
    public String component5() {
        return getStatus();
    }

    @Override
    public String component6() {
        return getAlarmRule();
    }

    @Override
    public String component7() {
        return getRuleAction();
    }

    @Override
    public String component8() {
        return getAlarmNotice();
    }

    @Override
    public String component9() {
        return getCreateBy();
    }

    @Override
    public String component10() {
        return getContext();
    }

    @Override
    public LocalDateTime component11() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime component12() {
        return getUpdatedTime();
    }

    @Override
    public String component13() {
        return getCombinationType();
    }

    @Override
    public String component14() {
        return getAccessToken();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAlarmName();
    }

    @Override
    public String value3() {
        return getAppName();
    }

    @Override
    public Integer value4() {
        return getAppId();
    }

    @Override
    public String value5() {
        return getStatus();
    }

    @Override
    public String value6() {
        return getAlarmRule();
    }

    @Override
    public String value7() {
        return getRuleAction();
    }

    @Override
    public String value8() {
        return getAlarmNotice();
    }

    @Override
    public String value9() {
        return getCreateBy();
    }

    @Override
    public String value10() {
        return getContext();
    }

    @Override
    public LocalDateTime value11() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime value12() {
        return getUpdatedTime();
    }

    @Override
    public String value13() {
        return getCombinationType();
    }

    @Override
    public String value14() {
        return getAccessToken();
    }

    @Override
    public AlarmRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AlarmRecord value2(String value) {
        setAlarmName(value);
        return this;
    }

    @Override
    public AlarmRecord value3(String value) {
        setAppName(value);
        return this;
    }

    @Override
    public AlarmRecord value4(Integer value) {
        setAppId(value);
        return this;
    }

    @Override
    public AlarmRecord value5(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public AlarmRecord value6(String value) {
        setAlarmRule(value);
        return this;
    }

    @Override
    public AlarmRecord value7(String value) {
        setRuleAction(value);
        return this;
    }

    @Override
    public AlarmRecord value8(String value) {
        setAlarmNotice(value);
        return this;
    }

    @Override
    public AlarmRecord value9(String value) {
        setCreateBy(value);
        return this;
    }

    @Override
    public AlarmRecord value10(String value) {
        setContext(value);
        return this;
    }

    @Override
    public AlarmRecord value11(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public AlarmRecord value12(LocalDateTime value) {
        setUpdatedTime(value);
        return this;
    }

    @Override
    public AlarmRecord value13(String value) {
        setCombinationType(value);
        return this;
    }

    @Override
    public AlarmRecord value14(String value) {
        setAccessToken(value);
        return this;
    }

    @Override
    public AlarmRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6, String value7, String value8, String value9, String value10, LocalDateTime value11, LocalDateTime value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlarmRecord
     */
    public AlarmRecord() {
        super(Alarm.ALARM);
    }

    /**
     * Create a detached, initialised AlarmRecord
     */
    public AlarmRecord(Integer id, String alarmName, String appName, Integer appId, String status, String alarmRule, String ruleAction, String alarmNotice, String createBy, String context, LocalDateTime createdTime, LocalDateTime updatedTime, String combinationType, String accessToken) {
        super(Alarm.ALARM);

        setId(id);
        setAlarmName(alarmName);
        setAppName(appName);
        setAppId(appId);
        setStatus(status);
        setAlarmRule(alarmRule);
        setRuleAction(ruleAction);
        setAlarmNotice(alarmNotice);
        setCreateBy(createBy);
        setContext(context);
        setCreatedTime(createdTime);
        setUpdatedTime(updatedTime);
        setCombinationType(combinationType);
        setAccessToken(accessToken);
    }
}
