/*
 * This file is generated by jOOQ.
 */
package com.alipay.autotuneservice.dao.jooq.tables.records;


import com.alipay.autotuneservice.dao.jooq.tables.CommandInfo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CommandInfoRecord extends UpdatableRecordImpl<CommandInfoRecord> implements Record12<Integer, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>TMAESTRO-LITE.COMMAND_INFO.ID</code>. 主键ID
     */
    public CommandInfoRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.COMMAND_INFO.ID</code>. 主键ID
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.COMMAND_INFO.SESSIONID</code>. 会话ID
     */
    public CommandInfoRecord setSessionid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.COMMAND_INFO.SESSIONID</code>. 会话ID
     */
    public String getSessionid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.COMMAND_INFO.RUNLE_ACTION</code>. 执行类型
     */
    public CommandInfoRecord setRunleAction(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.COMMAND_INFO.RUNLE_ACTION</code>. 执行类型
     */
    public String getRunleAction() {
        return (String) get(2);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.COMMAND_INFO.RESULT_TYPE</code>. 结果类型
     */
    public CommandInfoRecord setResultType(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.COMMAND_INFO.RESULT_TYPE</code>. 结果类型
     */
    public String getResultType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.COMMAND_INFO.RESULT</code>. 结果
     */
    public CommandInfoRecord setResult(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.COMMAND_INFO.RESULT</code>. 结果
     */
    public String getResult() {
        return (String) get(4);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.COMMAND_INFO.ACCESS_TOKEN</code>. 关联的token
     */
    public CommandInfoRecord setAccessToken(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.COMMAND_INFO.ACCESS_TOKEN</code>. 关联的token
     */
    public String getAccessToken() {
        return (String) get(5);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.COMMAND_INFO.APP_NAME</code>. 应用名
     */
    public CommandInfoRecord setAppName(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.COMMAND_INFO.APP_NAME</code>. 应用名
     */
    public String getAppName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.COMMAND_INFO.UNION_CODE</code>. 每个VM启动后,自动生成唯一标识,用来进行唯一关联
     */
    public CommandInfoRecord setUnionCode(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.COMMAND_INFO.UNION_CODE</code>. 每个VM启动后,自动生成唯一标识,用来进行唯一关联
     */
    public String getUnionCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.COMMAND_INFO.CONTEXT</code>. 执行上下文
     */
    public CommandInfoRecord setContext(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.COMMAND_INFO.CONTEXT</code>. 执行上下文
     */
    public String getContext() {
        return (String) get(8);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.COMMAND_INFO.STATUS</code>. 执行状态
     */
    public CommandInfoRecord setStatus(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.COMMAND_INFO.STATUS</code>. 执行状态
     */
    public String getStatus() {
        return (String) get(9);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.COMMAND_INFO.CREATED_TIME</code>. 创建时间
     */
    public CommandInfoRecord setCreatedTime(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.COMMAND_INFO.CREATED_TIME</code>. 创建时间
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.COMMAND_INFO.UPDATED_TIME</code>. 更新时间
     */
    public CommandInfoRecord setUpdatedTime(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.COMMAND_INFO.UPDATED_TIME</code>. 更新时间
     */
    public LocalDateTime getUpdatedTime() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Integer, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CommandInfo.COMMAND_INFO.ID;
    }

    @Override
    public Field<String> field2() {
        return CommandInfo.COMMAND_INFO.SESSIONID;
    }

    @Override
    public Field<String> field3() {
        return CommandInfo.COMMAND_INFO.RUNLE_ACTION;
    }

    @Override
    public Field<String> field4() {
        return CommandInfo.COMMAND_INFO.RESULT_TYPE;
    }

    @Override
    public Field<String> field5() {
        return CommandInfo.COMMAND_INFO.RESULT;
    }

    @Override
    public Field<String> field6() {
        return CommandInfo.COMMAND_INFO.ACCESS_TOKEN;
    }

    @Override
    public Field<String> field7() {
        return CommandInfo.COMMAND_INFO.APP_NAME;
    }

    @Override
    public Field<String> field8() {
        return CommandInfo.COMMAND_INFO.UNION_CODE;
    }

    @Override
    public Field<String> field9() {
        return CommandInfo.COMMAND_INFO.CONTEXT;
    }

    @Override
    public Field<String> field10() {
        return CommandInfo.COMMAND_INFO.STATUS;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return CommandInfo.COMMAND_INFO.CREATED_TIME;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return CommandInfo.COMMAND_INFO.UPDATED_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSessionid();
    }

    @Override
    public String component3() {
        return getRunleAction();
    }

    @Override
    public String component4() {
        return getResultType();
    }

    @Override
    public String component5() {
        return getResult();
    }

    @Override
    public String component6() {
        return getAccessToken();
    }

    @Override
    public String component7() {
        return getAppName();
    }

    @Override
    public String component8() {
        return getUnionCode();
    }

    @Override
    public String component9() {
        return getContext();
    }

    @Override
    public String component10() {
        return getStatus();
    }

    @Override
    public LocalDateTime component11() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime component12() {
        return getUpdatedTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSessionid();
    }

    @Override
    public String value3() {
        return getRunleAction();
    }

    @Override
    public String value4() {
        return getResultType();
    }

    @Override
    public String value5() {
        return getResult();
    }

    @Override
    public String value6() {
        return getAccessToken();
    }

    @Override
    public String value7() {
        return getAppName();
    }

    @Override
    public String value8() {
        return getUnionCode();
    }

    @Override
    public String value9() {
        return getContext();
    }

    @Override
    public String value10() {
        return getStatus();
    }

    @Override
    public LocalDateTime value11() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime value12() {
        return getUpdatedTime();
    }

    @Override
    public CommandInfoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CommandInfoRecord value2(String value) {
        setSessionid(value);
        return this;
    }

    @Override
    public CommandInfoRecord value3(String value) {
        setRunleAction(value);
        return this;
    }

    @Override
    public CommandInfoRecord value4(String value) {
        setResultType(value);
        return this;
    }

    @Override
    public CommandInfoRecord value5(String value) {
        setResult(value);
        return this;
    }

    @Override
    public CommandInfoRecord value6(String value) {
        setAccessToken(value);
        return this;
    }

    @Override
    public CommandInfoRecord value7(String value) {
        setAppName(value);
        return this;
    }

    @Override
    public CommandInfoRecord value8(String value) {
        setUnionCode(value);
        return this;
    }

    @Override
    public CommandInfoRecord value9(String value) {
        setContext(value);
        return this;
    }

    @Override
    public CommandInfoRecord value10(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public CommandInfoRecord value11(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public CommandInfoRecord value12(LocalDateTime value) {
        setUpdatedTime(value);
        return this;
    }

    @Override
    public CommandInfoRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, LocalDateTime value11, LocalDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CommandInfoRecord
     */
    public CommandInfoRecord() {
        super(CommandInfo.COMMAND_INFO);
    }

    /**
     * Create a detached, initialised CommandInfoRecord
     */
    public CommandInfoRecord(Integer id, String sessionid, String runleAction, String resultType, String result, String accessToken, String appName, String unionCode, String context, String status, LocalDateTime createdTime, LocalDateTime updatedTime) {
        super(CommandInfo.COMMAND_INFO);

        setId(id);
        setSessionid(sessionid);
        setRunleAction(runleAction);
        setResultType(resultType);
        setResult(result);
        setAccessToken(accessToken);
        setAppName(appName);
        setUnionCode(unionCode);
        setContext(context);
        setStatus(status);
        setCreatedTime(createdTime);
        setUpdatedTime(updatedTime);
    }
}
