/*
 * This file is generated by jOOQ.
 */
package com.alipay.autotuneservice.dao.jooq.tables.records;


import com.alipay.autotuneservice.dao.jooq.tables.NodeInfo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NodeInfoRecord extends UpdatableRecordImpl<NodeInfoRecord> implements Record8<Integer, String, String, String, LocalDateTime, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>TMAESTRO-LITE.NODE_INFO.ID</code>. 主键ID
     */
    public NodeInfoRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.NODE_INFO.ID</code>. 主键ID
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.NODE_INFO.NODE_NAME</code>. 节点名称
     */
    public NodeInfoRecord setNodeName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.NODE_INFO.NODE_NAME</code>. 节点名称
     */
    public String getNodeName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.NODE_INFO.IP</code>. IP地址
     */
    public NodeInfoRecord setIp(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.NODE_INFO.IP</code>. IP地址
     */
    public String getIp() {
        return (String) get(2);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.NODE_INFO.STATUS</code>. 状态;状态;包含：存活、失效
     */
    public NodeInfoRecord setStatus(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.NODE_INFO.STATUS</code>. 状态;状态;包含：存活、失效
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.NODE_INFO.CREATED_TIME</code>. 创建时间
     */
    public NodeInfoRecord setCreatedTime(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.NODE_INFO.CREATED_TIME</code>. 创建时间
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.NODE_INFO.NODE_TAGS</code>. 标签
     */
    public NodeInfoRecord setNodeTags(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.NODE_INFO.NODE_TAGS</code>. 标签
     */
    public String getNodeTags() {
        return (String) get(5);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.NODE_INFO.ACCESS_TOKEN</code>. 关联的token
     */
    public NodeInfoRecord setAccessToken(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.NODE_INFO.ACCESS_TOKEN</code>. 关联的token
     */
    public String getAccessToken() {
        return (String) get(6);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.NODE_INFO.UPDATED_TIME</code>.
     */
    public NodeInfoRecord setUpdatedTime(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.NODE_INFO.UPDATED_TIME</code>.
     */
    public LocalDateTime getUpdatedTime() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, String, LocalDateTime, String, String, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, String, LocalDateTime, String, String, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return NodeInfo.NODE_INFO.ID;
    }

    @Override
    public Field<String> field2() {
        return NodeInfo.NODE_INFO.NODE_NAME;
    }

    @Override
    public Field<String> field3() {
        return NodeInfo.NODE_INFO.IP;
    }

    @Override
    public Field<String> field4() {
        return NodeInfo.NODE_INFO.STATUS;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return NodeInfo.NODE_INFO.CREATED_TIME;
    }

    @Override
    public Field<String> field6() {
        return NodeInfo.NODE_INFO.NODE_TAGS;
    }

    @Override
    public Field<String> field7() {
        return NodeInfo.NODE_INFO.ACCESS_TOKEN;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return NodeInfo.NODE_INFO.UPDATED_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getNodeName();
    }

    @Override
    public String component3() {
        return getIp();
    }

    @Override
    public String component4() {
        return getStatus();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedTime();
    }

    @Override
    public String component6() {
        return getNodeTags();
    }

    @Override
    public String component7() {
        return getAccessToken();
    }

    @Override
    public LocalDateTime component8() {
        return getUpdatedTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getNodeName();
    }

    @Override
    public String value3() {
        return getIp();
    }

    @Override
    public String value4() {
        return getStatus();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedTime();
    }

    @Override
    public String value6() {
        return getNodeTags();
    }

    @Override
    public String value7() {
        return getAccessToken();
    }

    @Override
    public LocalDateTime value8() {
        return getUpdatedTime();
    }

    @Override
    public NodeInfoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public NodeInfoRecord value2(String value) {
        setNodeName(value);
        return this;
    }

    @Override
    public NodeInfoRecord value3(String value) {
        setIp(value);
        return this;
    }

    @Override
    public NodeInfoRecord value4(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public NodeInfoRecord value5(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public NodeInfoRecord value6(String value) {
        setNodeTags(value);
        return this;
    }

    @Override
    public NodeInfoRecord value7(String value) {
        setAccessToken(value);
        return this;
    }

    @Override
    public NodeInfoRecord value8(LocalDateTime value) {
        setUpdatedTime(value);
        return this;
    }

    @Override
    public NodeInfoRecord values(Integer value1, String value2, String value3, String value4, LocalDateTime value5, String value6, String value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NodeInfoRecord
     */
    public NodeInfoRecord() {
        super(NodeInfo.NODE_INFO);
    }

    /**
     * Create a detached, initialised NodeInfoRecord
     */
    public NodeInfoRecord(Integer id, String nodeName, String ip, String status, LocalDateTime createdTime, String nodeTags, String accessToken, LocalDateTime updatedTime) {
        super(NodeInfo.NODE_INFO);

        setId(id);
        setNodeName(nodeName);
        setIp(ip);
        setStatus(status);
        setCreatedTime(createdTime);
        setNodeTags(nodeTags);
        setAccessToken(accessToken);
        setUpdatedTime(updatedTime);
    }
}
