/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * This file is generated by jOOQ.
 */
package com.alipay.autotuneservice.dao.jooq.tables.records;


import com.alipay.autotuneservice.dao.jooq.tables.Notify;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotifyRecord extends UpdatableRecordImpl<NotifyRecord> implements Record8<Integer, String, String, String, LocalDateTime, LocalDateTime, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>TMAESTRO-LITE.NOTIFY.ID</code>.
     */
    public NotifyRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.NOTIFY.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.NOTIFY.GROUP_NAME</code>.
     */
    public NotifyRecord setGroupName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.NOTIFY.GROUP_NAME</code>.
     */
    public String getGroupName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.NOTIFY.STATUS</code>.
     */
    public NotifyRecord setStatus(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.NOTIFY.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.NOTIFY.CREATE_BY</code>.
     */
    public NotifyRecord setCreateBy(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.NOTIFY.CREATE_BY</code>.
     */
    public String getCreateBy() {
        return (String) get(3);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.NOTIFY.CREATED_TIME</code>.
     */
    public NotifyRecord setCreatedTime(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.NOTIFY.CREATED_TIME</code>.
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.NOTIFY.UPDATED_TIME</code>.
     */
    public NotifyRecord setUpdatedTime(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.NOTIFY.UPDATED_TIME</code>.
     */
    public LocalDateTime getUpdatedTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.NOTIFY.CONTEXT</code>.
     */
    public NotifyRecord setContext(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.NOTIFY.CONTEXT</code>.
     */
    public String getContext() {
        return (String) get(6);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.NOTIFY.ACCESS_TOKEN</code>.
     */
    public NotifyRecord setAccessToken(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.NOTIFY.ACCESS_TOKEN</code>.
     */
    public String getAccessToken() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, String, String, String, LocalDateTime, LocalDateTime, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, String, String, String, LocalDateTime, LocalDateTime, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Notify.NOTIFY.ID;
    }

    @Override
    public Field<String> field2() {
        return Notify.NOTIFY.GROUP_NAME;
    }

    @Override
    public Field<String> field3() {
        return Notify.NOTIFY.STATUS;
    }

    @Override
    public Field<String> field4() {
        return Notify.NOTIFY.CREATE_BY;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Notify.NOTIFY.CREATED_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Notify.NOTIFY.UPDATED_TIME;
    }

    @Override
    public Field<String> field7() {
        return Notify.NOTIFY.CONTEXT;
    }

    @Override
    public Field<String> field8() {
        return Notify.NOTIFY.ACCESS_TOKEN;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getGroupName();
    }

    @Override
    public String component3() {
        return getStatus();
    }

    @Override
    public String component4() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdatedTime();
    }

    @Override
    public String component7() {
        return getContext();
    }

    @Override
    public String component8() {
        return getAccessToken();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getGroupName();
    }

    @Override
    public String value3() {
        return getStatus();
    }

    @Override
    public String value4() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdatedTime();
    }

    @Override
    public String value7() {
        return getContext();
    }

    @Override
    public String value8() {
        return getAccessToken();
    }

    @Override
    public NotifyRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public NotifyRecord value2(String value) {
        setGroupName(value);
        return this;
    }

    @Override
    public NotifyRecord value3(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public NotifyRecord value4(String value) {
        setCreateBy(value);
        return this;
    }

    @Override
    public NotifyRecord value5(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public NotifyRecord value6(LocalDateTime value) {
        setUpdatedTime(value);
        return this;
    }

    @Override
    public NotifyRecord value7(String value) {
        setContext(value);
        return this;
    }

    @Override
    public NotifyRecord value8(String value) {
        setAccessToken(value);
        return this;
    }

    @Override
    public NotifyRecord values(Integer value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotifyRecord
     */
    public NotifyRecord() {
        super(Notify.NOTIFY);
    }

    /**
     * Create a detached, initialised NotifyRecord
     */
    public NotifyRecord(Integer id, String groupName, String status, String createBy, LocalDateTime createdTime, LocalDateTime updatedTime, String context, String accessToken) {
        super(Notify.NOTIFY);

        setId(id);
        setGroupName(groupName);
        setStatus(status);
        setCreateBy(createBy);
        setCreatedTime(createdTime);
        setUpdatedTime(updatedTime);
        setContext(context);
        setAccessToken(accessToken);
    }
}
