/*
 * This file is generated by jOOQ.
 */
package com.alipay.autotuneservice.dao.jooq.tables.records;


import com.alipay.autotuneservice.dao.jooq.tables.TwatchInfo;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TwatchInfoRecord extends TableRecordImpl<TwatchInfoRecord> implements Record9<String, String, String, String, String, Long, Long, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>TMAESTRO-LITE.TWATCH_INFO.CONTAINER_ID</code>. cantainer Id
     */
    public TwatchInfoRecord setContainerId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TWATCH_INFO.CONTAINER_ID</code>. cantainer Id
     */
    public String getContainerId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TWATCH_INFO.CONTAINER_NAME</code>. 容器名称
     */
    public TwatchInfoRecord setContainerName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TWATCH_INFO.CONTAINER_NAME</code>. 容器名称
     */
    public String getContainerName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TWATCH_INFO.NAMESPACE</code>. 容器所在namespace
     */
    public TwatchInfoRecord setNamespace(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TWATCH_INFO.NAMESPACE</code>. 容器所在namespace
     */
    public String getNamespace() {
        return (String) get(2);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TWATCH_INFO.POD_NAME</code>. pod name
     */
    public TwatchInfoRecord setPodName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TWATCH_INFO.POD_NAME</code>. pod name
     */
    public String getPodName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TWATCH_INFO.AGENT_NAME</code>. twatch demonset pod name
     */
    public TwatchInfoRecord setAgentName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TWATCH_INFO.AGENT_NAME</code>. twatch demonset pod name
     */
    public String getAgentName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TWATCH_INFO.GMT_MODIFIED</code>. 修改时间
     */
    public TwatchInfoRecord setGmtModified(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TWATCH_INFO.GMT_MODIFIED</code>. 修改时间
     */
    public Long getGmtModified() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TWATCH_INFO.DT_PERIOD</code>. 按天分区
     */
    public TwatchInfoRecord setDtPeriod(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TWATCH_INFO.DT_PERIOD</code>. 按天分区
     */
    public Long getDtPeriod() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TWATCH_INFO.NODE_NAME</code>. node name
     */
    public TwatchInfoRecord setNodeName(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TWATCH_INFO.NODE_NAME</code>. node name
     */
    public String getNodeName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.TWATCH_INFO.NODE_IP</code>. node ip
     */
    public TwatchInfoRecord setNodeIp(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.TWATCH_INFO.NODE_IP</code>. node ip
     */
    public String getNodeIp() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<String, String, String, String, String, Long, Long, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<String, String, String, String, String, Long, Long, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TwatchInfo.TWATCH_INFO.CONTAINER_ID;
    }

    @Override
    public Field<String> field2() {
        return TwatchInfo.TWATCH_INFO.CONTAINER_NAME;
    }

    @Override
    public Field<String> field3() {
        return TwatchInfo.TWATCH_INFO.NAMESPACE;
    }

    @Override
    public Field<String> field4() {
        return TwatchInfo.TWATCH_INFO.POD_NAME;
    }

    @Override
    public Field<String> field5() {
        return TwatchInfo.TWATCH_INFO.AGENT_NAME;
    }

    @Override
    public Field<Long> field6() {
        return TwatchInfo.TWATCH_INFO.GMT_MODIFIED;
    }

    @Override
    public Field<Long> field7() {
        return TwatchInfo.TWATCH_INFO.DT_PERIOD;
    }

    @Override
    public Field<String> field8() {
        return TwatchInfo.TWATCH_INFO.NODE_NAME;
    }

    @Override
    public Field<String> field9() {
        return TwatchInfo.TWATCH_INFO.NODE_IP;
    }

    @Override
    public String component1() {
        return getContainerId();
    }

    @Override
    public String component2() {
        return getContainerName();
    }

    @Override
    public String component3() {
        return getNamespace();
    }

    @Override
    public String component4() {
        return getPodName();
    }

    @Override
    public String component5() {
        return getAgentName();
    }

    @Override
    public Long component6() {
        return getGmtModified();
    }

    @Override
    public Long component7() {
        return getDtPeriod();
    }

    @Override
    public String component8() {
        return getNodeName();
    }

    @Override
    public String component9() {
        return getNodeIp();
    }

    @Override
    public String value1() {
        return getContainerId();
    }

    @Override
    public String value2() {
        return getContainerName();
    }

    @Override
    public String value3() {
        return getNamespace();
    }

    @Override
    public String value4() {
        return getPodName();
    }

    @Override
    public String value5() {
        return getAgentName();
    }

    @Override
    public Long value6() {
        return getGmtModified();
    }

    @Override
    public Long value7() {
        return getDtPeriod();
    }

    @Override
    public String value8() {
        return getNodeName();
    }

    @Override
    public String value9() {
        return getNodeIp();
    }

    @Override
    public TwatchInfoRecord value1(String value) {
        setContainerId(value);
        return this;
    }

    @Override
    public TwatchInfoRecord value2(String value) {
        setContainerName(value);
        return this;
    }

    @Override
    public TwatchInfoRecord value3(String value) {
        setNamespace(value);
        return this;
    }

    @Override
    public TwatchInfoRecord value4(String value) {
        setPodName(value);
        return this;
    }

    @Override
    public TwatchInfoRecord value5(String value) {
        setAgentName(value);
        return this;
    }

    @Override
    public TwatchInfoRecord value6(Long value) {
        setGmtModified(value);
        return this;
    }

    @Override
    public TwatchInfoRecord value7(Long value) {
        setDtPeriod(value);
        return this;
    }

    @Override
    public TwatchInfoRecord value8(String value) {
        setNodeName(value);
        return this;
    }

    @Override
    public TwatchInfoRecord value9(String value) {
        setNodeIp(value);
        return this;
    }

    @Override
    public TwatchInfoRecord values(String value1, String value2, String value3, String value4, String value5, Long value6, Long value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TwatchInfoRecord
     */
    public TwatchInfoRecord() {
        super(TwatchInfo.TWATCH_INFO);
    }

    /**
     * Create a detached, initialised TwatchInfoRecord
     */
    public TwatchInfoRecord(String containerId, String containerName, String namespace, String podName, String agentName, Long gmtModified, Long dtPeriod, String nodeName, String nodeIp) {
        super(TwatchInfo.TWATCH_INFO);

        setContainerId(containerId);
        setContainerName(containerName);
        setNamespace(namespace);
        setPodName(podName);
        setAgentName(agentName);
        setGmtModified(gmtModified);
        setDtPeriod(dtPeriod);
        setNodeName(nodeName);
        setNodeIp(nodeIp);
    }
}
