/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * This file is generated by jOOQ.
 */
package com.alipay.autotuneservice.dao.jooq.tables.records;


import com.alipay.autotuneservice.dao.jooq.tables.UserInfo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfoRecord extends UpdatableRecordImpl<UserInfoRecord> implements Record10<Integer, String, String, String, String, LocalDateTime, LocalDateTime, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>TMAESTRO-LITE.USER_INFO.ID</code>. 主键ID
     */
    public UserInfoRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.USER_INFO.ID</code>. 主键ID
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.USER_INFO.ACCOUNT_ID</code>. 关联的AWS用户ID
     */
    public UserInfoRecord setAccountId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.USER_INFO.ACCOUNT_ID</code>. 关联的AWS用户ID
     */
    public String getAccountId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.USER_INFO.ACCESS_TOKEN</code>. 关联的token
     */
    public UserInfoRecord setAccessToken(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.USER_INFO.ACCESS_TOKEN</code>. 关联的token
     */
    public String getAccessToken() {
        return (String) get(2);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.USER_INFO.USER_COMPANY</code>. 所属公司
     */
    public UserInfoRecord setUserCompany(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.USER_INFO.USER_COMPANY</code>. 所属公司
     */
    public String getUserCompany() {
        return (String) get(3);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.USER_INFO.USER_NAME</code>. 名称
     */
    public UserInfoRecord setUserName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.USER_INFO.USER_NAME</code>. 名称
     */
    public String getUserName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.USER_INFO.CREATED_TIME</code>. 创建时间
     */
    public UserInfoRecord setCreatedTime(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.USER_INFO.CREATED_TIME</code>. 创建时间
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.USER_INFO.UPDATED_TIME</code>. 更新时间
     */
    public UserInfoRecord setUpdatedTime(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.USER_INFO.UPDATED_TIME</code>. 更新时间
     */
    public LocalDateTime getUpdatedTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.USER_INFO.TENANT_CODE</code>. 租户

     */
    public UserInfoRecord setTenantCode(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.USER_INFO.TENANT_CODE</code>. 租户

     */
    public String getTenantCode() {
        return (String) get(7);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.USER_INFO.PRODUCT_ACCOUNT_ID</code>. 产品账户
     */
    public UserInfoRecord setProductAccountId(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.USER_INFO.PRODUCT_ACCOUNT_ID</code>. 产品账户
     */
    public String getProductAccountId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>TMAESTRO-LITE.USER_INFO.PLAN_CODE</code>.
     */
    public UserInfoRecord setPlanCode(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>TMAESTRO-LITE.USER_INFO.PLAN_CODE</code>.
     */
    public String getPlanCode() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, String, String, LocalDateTime, LocalDateTime, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, String, String, String, LocalDateTime, LocalDateTime, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserInfo.USER_INFO.ID;
    }

    @Override
    public Field<String> field2() {
        return UserInfo.USER_INFO.ACCOUNT_ID;
    }

    @Override
    public Field<String> field3() {
        return UserInfo.USER_INFO.ACCESS_TOKEN;
    }

    @Override
    public Field<String> field4() {
        return UserInfo.USER_INFO.USER_COMPANY;
    }

    @Override
    public Field<String> field5() {
        return UserInfo.USER_INFO.USER_NAME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return UserInfo.USER_INFO.CREATED_TIME;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return UserInfo.USER_INFO.UPDATED_TIME;
    }

    @Override
    public Field<String> field8() {
        return UserInfo.USER_INFO.TENANT_CODE;
    }

    @Override
    public Field<String> field9() {
        return UserInfo.USER_INFO.PRODUCT_ACCOUNT_ID;
    }

    @Override
    public Field<String> field10() {
        return UserInfo.USER_INFO.PLAN_CODE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAccountId();
    }

    @Override
    public String component3() {
        return getAccessToken();
    }

    @Override
    public String component4() {
        return getUserCompany();
    }

    @Override
    public String component5() {
        return getUserName();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime component7() {
        return getUpdatedTime();
    }

    @Override
    public String component8() {
        return getTenantCode();
    }

    @Override
    public String component9() {
        return getProductAccountId();
    }

    @Override
    public String component10() {
        return getPlanCode();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAccountId();
    }

    @Override
    public String value3() {
        return getAccessToken();
    }

    @Override
    public String value4() {
        return getUserCompany();
    }

    @Override
    public String value5() {
        return getUserName();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime value7() {
        return getUpdatedTime();
    }

    @Override
    public String value8() {
        return getTenantCode();
    }

    @Override
    public String value9() {
        return getProductAccountId();
    }

    @Override
    public String value10() {
        return getPlanCode();
    }

    @Override
    public UserInfoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserInfoRecord value2(String value) {
        setAccountId(value);
        return this;
    }

    @Override
    public UserInfoRecord value3(String value) {
        setAccessToken(value);
        return this;
    }

    @Override
    public UserInfoRecord value4(String value) {
        setUserCompany(value);
        return this;
    }

    @Override
    public UserInfoRecord value5(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public UserInfoRecord value6(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public UserInfoRecord value7(LocalDateTime value) {
        setUpdatedTime(value);
        return this;
    }

    @Override
    public UserInfoRecord value8(String value) {
        setTenantCode(value);
        return this;
    }

    @Override
    public UserInfoRecord value9(String value) {
        setProductAccountId(value);
        return this;
    }

    @Override
    public UserInfoRecord value10(String value) {
        setPlanCode(value);
        return this;
    }

    @Override
    public UserInfoRecord values(Integer value1, String value2, String value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserInfoRecord
     */
    public UserInfoRecord() {
        super(UserInfo.USER_INFO);
    }

    /**
     * Create a detached, initialised UserInfoRecord
     */
    public UserInfoRecord(Integer id, String accountId, String accessToken, String userCompany, String userName, LocalDateTime createdTime, LocalDateTime updatedTime, String tenantCode, String productAccountId, String planCode) {
        super(UserInfo.USER_INFO);

        setId(id);
        setAccountId(accountId);
        setAccessToken(accessToken);
        setUserCompany(userCompany);
        setUserName(userName);
        setCreatedTime(createdTime);
        setUpdatedTime(updatedTime);
        setTenantCode(tenantCode);
        setProductAccountId(productAccountId);
        setPlanCode(planCode);
    }
}
